name: Deploy

on:
  push:
    branches: [main]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    continue-on-error: true
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          cd development/xdrinks-frontend/
          git pull
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh 
          npm install pm2 -g
          pm2 delete --silent xdrinks-frontend
          npm ci
          npm run build --if-present
          pm2 start npm --name "xdrinks-frontend" -- start -- --port 3100
